---
- name: Set /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 ubuntu-20'

- name: Set /etc/hostname
  become: yes
  lineinfile:
    path: /etc/hostname
    regexp: '.*'
    line: ubuntu-20

- name: Set hostname
  become: yes
  hostname:
    name: ubuntu-20