---
- hosts: localhost
  connection: local
  become: yes
  become_user: root
  vars:
    user: "jlester"
    email: "jlester@velocityrisk.com"
    name: "Josh Lester"
  roles:
    # - role: hostname
    #   tags: hostname

    - role: common
      tags: common

    - role: user
      tags: user

    - role: software-base
      tags: software-base

    - role: fonts
      tags: fonts

    - role: docker
      tags: docker

    - role: nodejs
      tags: nodejs

    - role: dotnet
      tags: dotnet

    - role: kubectl
      tags: kubectl

    - role: npm
      tags: npm

    - role: zsh
      tags: zsh

    # - role: npm
    #   tags: npm

    # - role: wallpaper
    #   tags: wallpaper
      
    - command: git config --global alias.co checkout; git config --global alias.br branch; git config --global alias.ci commit; git config --global alias.st status  
