---
- hosts: localhost
  roles:
    # - role: xps_9560
    #   tags: hardware
    #   when: ansible_product_name == "XPS 15 9560"

    - role: hostname
      tags: hostname

    - role: common
      tags: common

    - role: user
      tags: user

    - role: zsh_theme
      tags: zsh_theme

    - role: npm
      tags: npm

    # - role: keyboard_shortcuts
    #   tags: keyboard_shortcuts

    - role: wallpaper
      tags: wallpaper
      
    - command: git config --global alias.co checkout; git config --global alias.br branch; git config --global alias.ci commit; git config --global alias.st status  
