
---
- hosts: localhost
  connection: local
  become: yes
  become_user: root
  vars_files: vars.yaml
  roles:
    - utilities-base
    - git
    - fonts
    - docker
    - nodejs
    - az-cli
    - kubectl
    - dotnet
    - helm
    - liquibase
    - terraform
    - zsh
