---
- name: Create ~/bin
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: 0755

- name: User - shell to zsh, groups to docker
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    # generate_ssh_key: yes
    groups:
      - docker
      - plugdev
    shell: /usr/bin/zsh
    append: yes

- name: Set git co alias
  git_config:
    name: alias.co
    value: checkout
    scope: global

- name: Set git github include
  git_config:
    name: includeIf.gitdir:git/github.com/**.path
    value: .gitconfig-github.com
    scope: global

- name: github.com include
  copy:
    dest: "{{ ansible_env.HOME }}/.gitconfig-github.com"
    content: |
      [user]
      	name = "{{ user }}"
      	email = "{{ email }}"

- name: Do bad things with known_hosts
  blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    create: yes
    block: |
      host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null

- name: create git configuration
  copy:
    dest: "/home/{{ user }}/.gitconfig"
    content: |
      [user]
        name = "{{ name }}"
        email = "{{ email }}"
      [init]
        defaultBranch = main