---
# tasks file for docker
- name: add docker repo
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt update
  args:
    creates: /etc/apt/sources.list.d/docker.list
    # # warn: false
- name: install docker-ce
  package: 
    name: docker-ce
    state: present
- name: add "{{ user }}" to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes